### ISSUE TITLE
频繁发消息报异常。

### ISSUE THREAD

**Issue by Zziv** [xuuhaoo/OkSocket#28]
频繁的发 1
duplex read error,thread is dead with exception:com.xuhao.android.libsocket.impl.exceptions.ReadException: this socket input stream has some problem,wrong body length -1,we'll disconnect

**Comment by xuuhaoo** [comment]
有没有截图或者详细的描述

**Comment by 281922239** [comment]
W/System.err: com.xuhao.android.libsocket.impl.exceptions.ReadException: com.xuhao.android.libsocket.impl.exceptions.ReadException: channel maybe close, so we decided to shut it down
W/System.err:     at com.xuhao.android.libsocket.impl.nonblockio.nio.Reader.read(Reader.java:107)
W/System.err:     at com.xuhao.android.libsocket.impl.nonblockio.threads.DuplexReadThread.runInLoopThread(DuplexReadThread.java:66)
W/System.err:     at com.xuhao.android.libsocket.impl.LoopThread.run(LoopThread.java:50)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
W/System.err: Caused by: com.xuhao.android.libsocket.impl.exceptions.ReadException: channel maybe close, so we decided to shut it down
W/System.err:     at com.xuhao.android.libsocket.impl.nonblockio.nio.Reader.read(Reader.java:62)
W/System.err: 	... 3 more

**Comment by xuuhaoo** [comment]
这个异常是因为服务器断开了此次socket连接
