### ISSUE TITLE
transmission protocol issues,how to use the setHeaderProtocol method

### ISSUE THREAD

**Issue by indrakumarprajapat** [xuuhaoo/OkSocket#97]
Hi I am using, v2.0.3, connect and send messages working fine. but in receive message i got this error. I am using another tcp server app for sending messages to test.

```
duplex read error,thread is dead with exception:com.xuhao.android.libsocket.impl.exceptions.ReadException: Need to follow the transmission protocol.
                                                                    Please check the client/server code.
                                                                    According to the packet header data in the transport protocol, the package length is 1752000621 Bytes.
```

**Comment by xuuhaoo** [comment]
This error means you need follow the HeaderProtocol to receive messages from server .

**Comment by xuuhaoo** [comment]
![image](https://user-images.githubusercontent.com/10423664/43569014-da40496c-9668-11e8-9623-09f42364b2b8.png)
The Header in packages is blue area means.Other area is Body .

**Comment by indrakumarprajapat** [comment]
Thanks, xuuhaoo. I really appreciate if you can help me. I tried lot of libs but none is working except your to connect and send msg.
Can you let me know the implementation of these 2 methods, i guess getHeaderLength should return 4, i read about it. but i am not able to write the code for getBodyLength.

**Comment by xuuhaoo** [comment]
Thank you for your kindness
The situation what you got is cause you don't have a suitable HeaderProtocol .You can take a look as follow code by other developer write's:
![image](https://user-images.githubusercontent.com/10423664/43627303-5851bcae-9728-11e8-9f04-6e8c44c00199.png)
(note: Sorry code comments language is Chinese.)
As above code you need return the correct length of Body when Oksocket receive Package from server.
Oksocket needs fixed header length to cut stream pieces,because the stream consists header and body.
When Oksocket got the header According to the getHeaderLength() method then we need you told the Oksocket the body length,So you can parsing the body length from header bytes which we cut.

**Comment by Mkurbanov** [comment]
it's not working bro. Can you help me?

**Comment by tej-mpc** [comment]
Hello, can you send me a sample example of a message. if we follow default read protocol then which message is accept by your demo code? If i send message {"abc":123} like this. so how i have to send from your protocol. please help
